name: CI

on: [push]

jobs:
  test:
    name: Test on Node.js 12 running on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Install dependencies, lint and run all tests
        run: npm install

      - name: Run hydrate tests
        run: cd hydrate/tests && npm install && npm test
